name: Custom Workflow 

#Triggers workflow on every push to the main branch
on:
    push:
        branches: [main]

jobs:
    custom-task:
        runs-on: ubuntu-latest
    
        steps:
        - name: Running Custom Work flow
          run: echo "Custom work flow"

          #C\GEnertate release notes