name: Dependency Updates

#Triggers workflow on every push to the main branch
on:
    push:
        branches: [main]

jobs:
    dependency-updates:
        runs-on: ubuntu-latest
          
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Run dependency update
          run: echo "Project is up to date"
          #uses: dependabot/dependabot-core@master
          #with:
            #github_token: ${{ secrets.GITHUB_TOKEN }}
            #I am not implementing this ecause the actual code only runs on Node version 12
