name: Deployment Pipeline

#Triggers workflow on every push to the main branch
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        #checking out code
        - name: Checkout Repository
          uses: actions/checkout@v2
        - run: echo "Check out complete"

        #Setting up Node js
        - name: Setting up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '12.x' #README said 12.10.0 or higher
        - run: echo "Node.js is set up in container"

        #Installing dependencies
        - name: Install Dependencies
          run: npm install
        - run: echo "Dependencies Installed"

        #Building in case there is something in the code that needs it
        - name: Building the application
         # run: npm run build
          run: echo "Build is run"

        #Running Tests
        - name: Running Tests
          run: npm test
        - run: echo "Tests are run"

    #the deployment code
    deploy:
        needs: build #using things compiled from the build step
        runs-on: ubuntu-latest      
        steps:
        - name: Deploying to Heroku
          #uses: akhileshns/heroku-deploy@v3.12.12
          #with:
           # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
           # heroku_app_name: "your-heroku-app-name"
           # heroku_email: "your-email@example.com"
          run: echo "Deployment is complete"

        
