name: Documentation

# Triggers workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x' 

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: npm run docs:generate


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ASSIGNMENT_TOKEN }}
          publish_dir: ./docs # Adjust the directory where your generated documentation is located