name: Scheduled Tasks

on:
  push:
    branches: [main] #This is temporary the actual code is the schedule one
#  schedule: # I am doing this to stop it from running at night
   # - cron: '0 0 * * *' # Run daily at

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Maintenance of Code
      run: ./scripts/maintenance.sh

    - name: backing up data
      run: ./scripts/backup.sh

    - name: Notifying 
      run: ./scripts/notify.sh #do the email sending 
